version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - academy-net

  broker:
    image: nexweb1/cp-enterprise-kafka:klab-0.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,LOCAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LOCAL:PLAINTEXT
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - academy-net

  redis-master:
    container_name: "redis-master"
    image: redis
    ports:
      - "6379:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data/master:/data/"
      - "./master.conf:/etc/redis.conf"
    networks:
      - academy-net

  redis-slave:
    image: redis
    container_name: "redis-slave"
    ports:
      - "6388:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data/slave:/data/"
      - "./slave.conf:/etc/redis.conf"
    networks:
      - academy-net

  postgres:
    image: postgres:10
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgressql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/1-ddl.sql"
    environment:
      - POSTGRES_PASSWORD=passw0rd
    networks:
      - academy-net

  order:
    image: nexweb1/order
    hostname: order
    container_name: "order"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
      PRODUCT_URL: 'http://stock:8081/products'
      STOCK_URL: 'http://stock:8081/stocks'
      PAYMENT_URL: 'http://payment:8082/payments'
    depends_on:
      - postgres
    networks:
      - academy-net

  stock:
    image: nexweb1/stock
    hostname: stock
    container_name: "stock"
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: 'broker:29092'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
      SPRING_REDIS_HOST: 'redis-master'
    depends_on:
      - broker
      - redis-master
      - postgres
    networks:
      - academy-net
    links:
      - broker

  payment:
    image: nexweb1/payment
    hostname: payment
    container_name: "payment"
    ports:
      - "8082:8082"
    depends_on:
      - broker
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: 'broker:29092'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
    networks:
      - academy-net
    links:
      - broker

networks:
  academy-net:
